[
  { answer: "PARETO", clue: "Chart ranking causes by how often they occur" },
  { answer: "SENTINEL", clue: "Safety event demanding immediate investigation" },
  { answer: "SAFE", clue: "IOM aim: avoiding injury from care meant to help" },
  { answer: "EFFECTIVE", clue: "IOM aim: care based on scientific knowledge" },
  { answer: "TIMELY", clue: "IOM aim: reducing harmful waits and delays" },
  { answer: "EFFICIENT", clue: "IOM aim: avoiding waste of supplies and energy" },
  { answer: "EQUITABLE", clue: "IOM aim: quality that does not vary by ethnicity" },
  { answer: "AIMS", clue: "The six goals named in Crossing the Quality Chasm" },
  { answer: "IOM", clue: "Body that issued To Err Is Human, in brief" },
  { answer: "CHASM", clue: "Word in the 2001 IOM quality report title" },
  { answer: "DONABEDIAN", clue: "Theorist of structure, process, and outcome" },
  { answer: "STRUCTURE", clue: "Donabedian element covering staffing and equipment" },
  { answer: "PROCESS", clue: "Donabedian element: what clinicians actually do" },
  { answer: "OUTCOME", clue: "Donabedian element: the result for the patient" },
  { answer: "BALANCING", clue: "Kind of measure watching for unintended harm" },
  { answer: "NUMERATOR", clue: "Top of a rate: cases meeting the criterion" },
  { answer: "DENOMINATOR", clue: "Bottom of a rate: the eligible population" },
  { answer: "EXCLUSION", clue: "Case removed from a measure's eligible pool" },
  { answer: "RATE", clue: "Count divided by a population at risk" },
  { answer: "RATIO", clue: "Observed over expected, for one" },
  { answer: "OBSERVED", clue: "Actual count, in an O/E comparison" },
  { answer: "EXPECTED", clue: "Predicted count after case-mix adjustment" },
  { answer: "SEVERITY", clue: "How sick the patient is; an FMEA rating too" },
  { answer: "CASEMIX", clue: "Complexity of a facility's patient population" },
  { answer: "COVARIATE", clue: "Patient factor entered into a risk model" },
  { answer: "BENCHMARK", clue: "Best-in-class figure used for comparison" },
  { answer: "THRESHOLD", clue: "Level that triggers review when crossed" },
  { answer: "TARGET", clue: "The number an improvement team aims to hit" },
  { answer: "GOAL", clue: "Stated aim of a performance project" },
  { answer: "BASELINE", clue: "Starting measurement before any change" },
  { answer: "TREND", clue: "Direction data moves over successive periods" },
  { answer: "INDICATOR", clue: "Quantifiable sign of performance" },
  { answer: "METRIC", clue: "Standardized unit of quality measurement" },
  { answer: "PDSA", clue: "Plan, Do, Study, Act, in short" },
  { answer: "PDCA", clue: "Shewhart cycle with Check in place of Study" },
  { answer: "DEMING", clue: "Quality guru of the 14 Points" },
  { answer: "JURAN", clue: "Trilogy man: planning, control, improvement" },
  { answer: "CROSBY", clue: "Guru who said quality is free" },
  { answer: "SHEWHART", clue: "Father of statistical process control" },
  { answer: "LEAN", clue: "Method stripping non-value-added steps" },
  { answer: "MUDA", clue: "Japanese term for waste in Lean" },
  { answer: "KAIZEN", clue: "Small continuous change for the better" },
  { answer: "GEMBA", clue: "The actual place where the work is done" },
  { answer: "FLOW", clue: "Smooth uninterrupted movement of work" },
  { answer: "PULL", clue: "System in which demand triggers the next step" },
  { answer: "KANBAN", clue: "Visual card signaling work in progress" },
  { answer: "FIVES", clue: "Sort, set, shine, standardize, sustain program" },
  { answer: "VALUE", clue: "What the customer is willing to pay for" },
  { answer: "STREAM", clue: "Word before mapping in a Lean flow study" },
  { answer: "WASTE", clue: "Any step the patient would not pay for" },
  { answer: "DEFECT", clue: "Output that fails to meet specification" },
  { answer: "SIGMA", clue: "Greek letter used for standard deviation" },
  { answer: "DMAIC", clue: "Six Sigma's five-phase improvement roadmap" },
  { answer: "DEFINE", clue: "First phase of the Six Sigma roadmap" },
  { answer: "ANALYZE", clue: "Roadmap phase hunting for root causes" },
  { answer: "IMPROVE", clue: "DMAIC phase where solutions are piloted" },
  { answer: "CONTROL", clue: "Last DMAIC phase; holding the gain" },
  { answer: "DMADV", clue: "Six Sigma roadmap for brand-new designs" },
  { answer: "BELT", clue: "Green or black rank in Six Sigma" },
  { answer: "CHAMPION", clue: "Executive sponsor of a Six Sigma project" },
  { answer: "VARIATION", clue: "Spread in a process; the enemy of quality" },
  { answer: "TQM", clue: "Total quality management, in brief" },
  { answer: "CQI", clue: "Continuous quality improvement, in brief" },
  { answer: "FOCUS", clue: "Find, organize, clarify, understand, select" },
  { answer: "RAPID", clue: "Kind of cycle testing tiny changes fast" },
  { answer: "CYCLE", clue: "One full turn of the plan-do-study-act loop" },
  { answer: "TEST", clue: "Small trial of a change on one patient" },
  { answer: "SPREAD", clue: "Taking a proven change house-wide" },
  { answer: "ADOPT", clue: "Keep a change after a successful trial" },
  { answer: "ADAPT", clue: "Modify a change before the next trial" },
  { answer: "ABANDON", clue: "Drop a change that failed its trial" },
  { answer: "WHY", clue: "Five of these drill down to a root cause" },
  { answer: "CHARTER", clue: "Document authorizing a project team's work" },
  { answer: "SPONSOR", clue: "Leader who removes barriers for a team" },
  { answer: "TEAM", clue: "Multidisciplinary group driving a project" },
  { answer: "FACILITATOR", clue: "Neutral person guiding a meeting's process" },
  { answer: "STAKEHOLDER", clue: "Anyone affected by the process being changed" },
  { answer: "CUSTOMER", clue: "Recipient of a process output" },
  { answer: "SUPPLIER", clue: "First element listed in a SIPOC diagram" },
  { answer: "SIPOC", clue: "High-level map running suppliers to customers" },
  { answer: "FLOWCHART", clue: "Boxes and arrows showing steps in order" },
  { answer: "SYMBOL", clue: "Diamond or rectangle in a process drawing" },
  { answer: "DIAMOND", clue: "Decision-point shape on a process drawing" },
  { answer: "MAP", clue: "Process picture of steps drawn in sequence" },
  { answer: "FISHBONE", clue: "Diagram whose shape suggests a skeleton" },
  { answer: "ISHIKAWA", clue: "Japanese name for the cause-and-effect chart" },
  { answer: "CAUSE", clue: "The why behind an unwanted effect" },
  { answer: "EFFECT", clue: "Problem written at the head of a fishbone" },
  { answer: "BONE", clue: "Category branch on an Ishikawa diagram" },
  { answer: "SPINE", clue: "Horizontal center line of a fishbone chart" },
  { answer: "EIGHTY", clue: "Percent of trouble from a fifth of causes" },
  { answer: "VITAL", clue: "Juran's few that cause most of the problems" },
  { answer: "TRIVIAL", clue: "Juran's word for the many minor causes" },
  { answer: "RUNCHART", clue: "Simple line graph plotting data over time" },
  { answer: "RUN", clue: "String of points on one side of the median" },
  { answer: "MEDIAN", clue: "Center line drawn on a run chart" },
  { answer: "MEAN", clue: "Arithmetic average of a data set" },
  { answer: "MODE", clue: "Most frequently occurring value" },
  { answer: "RANGE", clue: "Highest value minus the lowest" },
  { answer: "SHIFT", clue: "Six or more points on one side of the center" },
  { answer: "ASTRONOMICAL", clue: "Wildly out-of-place single data point" },
  { answer: "CONTROLCHART", clue: "Graph with limits three sigma from the mean" },
  { answer: "LIMIT", clue: "Upper or lower boundary line on an SPC graph" },
  { answer: "UCL", clue: "Top statistical boundary line, in brief" },
  { answer: "LCL", clue: "Bottom statistical boundary line, in brief" },
  { answer: "SPC", clue: "Statistical process control, in brief" },
  { answer: "COMMON", clue: "Kind of cause built into the process itself" },
  { answer: "SPECIAL", clue: "Kind of cause from something out of the ordinary" },
  { answer: "STABLE", clue: "Said of a process in statistical control" },
  { answer: "CAPABLE", clue: "Able to meet specification consistently" },
  { answer: "OUTLIER", clue: "Point lying far from the rest of the data" },
  { answer: "HISTOGRAM", clue: "Bar graph showing a frequency distribution" },
  { answer: "SCATTER", clue: "Plot revealing correlation between variables" },
  { answer: "CORRELATION", clue: "Relationship between two plotted variables" },
  { answer: "CHECKSHEET", clue: "Tally form for counting events as they occur" },
  { answer: "TALLY", clue: "Hash mark used to count occurrences" },
  { answer: "AFFINITY", clue: "Diagram grouping ideas into natural themes" },
  { answer: "BRAINSTORM", clue: "Rapid free listing of ideas without critique" },
  { answer: "NOMINAL", clue: "Group technique using silent ranked voting" },
  { answer: "MULTIVOTING", clue: "Narrowing a long list by repeated rounds" },
  { answer: "DRIVER", clue: "Diagram linking an aim to key contributing factors" },
  { answer: "DASHBOARD", clue: "Screen of real-time performance indicators" },
  { answer: "SCORECARD", clue: "Balanced tool tracking four perspectives" },
  { answer: "GANTT", clue: "Bar chart of project tasks over time" },
  { answer: "ERROR", clue: "Failure of a planned action to be completed" },
  { answer: "SLIP", clue: "Attention failure: right plan, wrong doing" },
  { answer: "LAPSE", clue: "Memory failure causing a step to be skipped" },
  { answer: "MISTAKE", clue: "Wrong plan carried out exactly as intended" },
  { answer: "ACTIVE", clue: "Kind of failure at the sharp end of care" },
  { answer: "LATENT", clue: "Hidden system flaw awaiting a trigger" },
  { answer: "SHARP", clue: "End of the system where the caregiver acts" },
  { answer: "BLUNT", clue: "End of the system where policy is set" },
  { answer: "SWISS", clue: "Cheese model of layered defenses, per Reason" },
  { answer: "HOLES", clue: "Gaps in the layers of Reason's cheese model" },
  { answer: "REASON", clue: "Psychologist behind the cheese model" },
  { answer: "ADVERSE", clue: "Kind of event bringing unintended injury" },
  { answer: "HARM", clue: "Physical or emotional injury from care" },
  { answer: "NEARMISS", clue: "Error caught before it reached the patient" },
  { answer: "CLOSECALL", clue: "Another term for a caught-in-time error" },
  { answer: "NEVER", clue: "Kind of event that should not happen at all" },
  { answer: "SRE", clue: "NQF list of egregious, largely preventable harms" },
  { answer: "HAC", clue: "Hospital-acquired condition, in brief" },
  { answer: "WRONGSITE", clue: "Describing surgery on the incorrect body part" },
  { answer: "RETAINED", clue: "Said of a sponge left inside a patient" },
  { answer: "PREVENTABLE", clue: "Said of harm that could have been avoided" },
  { answer: "MITIGATION", clue: "Action lessening the severity of an injury" },
  { answer: "RCA", clue: "Root cause analysis, in brief" },
  { answer: "ROOT", clue: "Deepest cause an investigation seeks" },
  { answer: "ANALYSIS", clue: "Systematic study following a sentinel event" },
  { answer: "CORRECTIVE", clue: "Kind of action plan closing an investigation" },
  { answer: "CONTRIBUTING", clue: "Kind of factor short of being a root cause" },
  { answer: "FMEA", clue: "Failure mode and effects analysis, in brief" },
  { answer: "FAILURE", clue: "Mode of breakdown studied before it happens" },
  { answer: "OCCURRENCE", clue: "How often a failure happens; an FMEA rating" },
  { answer: "DETECTION", clue: "Odds of catching a failure; an FMEA rating" },
  { answer: "RPN", clue: "Risk priority number, in brief" },
  { answer: "PROACTIVE", clue: "Looking ahead at what could go wrong" },
  { answer: "RETROSPECTIVE", clue: "Looking back after the event has occurred" },
  { answer: "HAZARD", clue: "Condition with the potential to cause harm" },
  { answer: "RISK", clue: "Chance of loss or injury" },
  { answer: "SAFETY", clue: "Freedom from accidental injury during care" },
  { answer: "TRIGGER", clue: "Clue in a record flagging possible harm" },
  { answer: "GLOBAL", clue: "Worldwide; also the IHI harm-measuring tool" },
  { answer: "FORCING", clue: "Kind of function making an error impossible" },
  { answer: "REDUNDANCY", clue: "Backup layer such as an independent recheck" },
  { answer: "STANDARDIZE", clue: "Cut variation by making steps uniform" },
  { answer: "CONSTRAINT", clue: "Design barrier blocking an unsafe action" },
  { answer: "ALERT", clue: "Pop-up warning in an electronic record" },
  { answer: "FATIGUE", clue: "Desensitization from too many pop-up warnings" },
  { answer: "JUST", clue: "Kind of culture balancing learning and accountability" },
  { answer: "HUMAN", clue: "Kind of error meriting consolation, not punishment" },
  { answer: "ATRISK", clue: "Kind of behavior whose danger goes unrecognized" },
  { answer: "RECKLESS", clue: "Conscious disregard of a substantial risk" },
  { answer: "CONSOLE", clue: "Fair response to an inadvertent human error" },
  { answer: "COACH", clue: "Fair response to drifting, unsafe behavior" },
  { answer: "DISCIPLINE", clue: "Fair response to a knowingly reckless choice" },
  { answer: "BLAME", clue: "Finger-pointing that silences event reporting" },
  { answer: "PUNITIVE", clue: "Describing the old culture of shame and train" },
  { answer: "INCIDENT", clue: "Kind of report filed after an unusual event" },
  { answer: "PSO", clue: "Patient safety organization, in brief" },
  { answer: "PSWP", clue: "Patient safety work product, in brief" },
  { answer: "PRIVILEGE", clue: "Legal shield keeping safety analyses out of court" },
  { answer: "DISCLOSURE", clue: "Telling a patient that harm has occurred" },
  { answer: "HUDDLE", clue: "Brief stand-up meeting at the start of a shift" },
  { answer: "DEBRIEF", clue: "Short review held right after a procedure" },
  { answer: "HANDOFF", clue: "Transfer of care responsibility between staff" },
  { answer: "SBAR", clue: "Situation, background, assessment, recommendation" },
  { answer: "READBACK", clue: "Repeating a verbal order to confirm accuracy" },
  { answer: "TIMEOUT", clue: "Pause before incision to verify the patient" },
  { answer: "UNIVERSAL", clue: "Protocol for preventing wrong-site surgery" },
  { answer: "REVIEW", clue: "Utilization check of need and level of care" },
  { answer: "PROSPECTIVE", clue: "Done before the service is delivered" },
  { answer: "CONCURRENT", clue: "Done while the patient is still hospitalized" },
  { answer: "NECESSITY", clue: "Medical justification a payer demands" },
  { answer: "CRITERIA", clue: "Screening rules such as InterQual or MCG" },
  { answer: "ADVISOR", clue: "Physician ruling on questionable admissions" },
  { answer: "DISCHARGE", clue: "Planning for this begins on the day of admission" },
  { answer: "OBSERVATION", clue: "Outpatient status short of inpatient admission" },
  { answer: "LOS", clue: "Length of stay, in brief" },
  { answer: "AVOIDABLE", clue: "Kind of hospital day caused by a service delay" },
  { answer: "DENIAL", clue: "Payer refusal to pay for a service" },
  { answer: "SURVEY", clue: "Unannounced on-site accreditation visit" },
  { answer: "TRACER", clue: "Method following one patient through the system" },
  { answer: "NPSG", clue: "National Patient Safety Goal, in brief" },
  { answer: "DEEMED", clue: "Kind of status standing in for a CMS inspection" },
  { answer: "HEDIS", clue: "NCQA measure set for health plan quality" },
  { answer: "SEPSIS", clue: "Life-threatening body response to infection" },
  { answer: "FALLS", clue: "Events reduced by bed alarms and hourly rounding" }
]
