[
  { answer: "ALOS", clue: "Average length of stay, in short" },
  { answer: "MEDIAN", clue: "Middle value in an ordered set" },
  { answer: "MEAN", clue: "Arithmetic average of a data set" },
  { answer: "MODE", clue: "Most frequently occurring value" },
  { answer: "RANGE", clue: "Highest value minus the lowest" },
  { answer: "VARIANCE", clue: "Square of the standard deviation" },
  { answer: "PERCENTILE", clue: "Rank showing percent of scores below" },
  { answer: "QUARTILE", clue: "One of four equal parts of ordered data" },
  { answer: "SKEW", clue: "Asymmetry of a distribution's tail" },
  { answer: "OUTLIER", clue: "Extreme value far from the rest" },
  { answer: "FREQUENCY", clue: "Count of times a value appears" },
  { answer: "BIMODAL", clue: "Describing a curve with two peaks" },
  { answer: "NORMAL", clue: "Type of bell-shaped curve" },
  { answer: "CURVE", clue: "Shape traced by a distribution's plot" },
  { answer: "SIGMA", clue: "Greek letter for standard deviation" },
  { answer: "SPREAD", clue: "How widely data values scatter" },
  { answer: "CENSUS", clue: "Count of inpatients at a given time" },
  { answer: "INPATIENT", clue: "Admitted patient occupying a bed" },
  { answer: "OUTPATIENT", clue: "Patient not formally admitted" },
  { answer: "DISCHARGE", clue: "Formal release of a patient from care" },
  { answer: "ADMISSION", clue: "Formal acceptance of a patient for care" },
  { answer: "BASSINET", clue: "Newborn's bed, counted separately" },
  { answer: "NEWBORN", clue: "Infant born within the facility" },
  { answer: "NEONATAL", clue: "Pertaining to the first 28 days of life" },
  { answer: "OCCUPANCY", clue: "Percent of beds in use" },
  { answer: "BEDCOUNT", clue: "Number of available facility beds" },
  { answer: "TRANSFER", clue: "Movement of a patient between units" },
  { answer: "LEAVE", clue: "Absence granted before a patient returns" },
  { answer: "MIDNIGHT", clue: "Hour at which daily census is taken" },
  { answer: "SERVICE", clue: "___ days: units of inpatient care given" },
  { answer: "MORTALITY", clue: "Death, in statistical terms" },
  { answer: "MORBIDITY", clue: "Illness or disease in a population" },
  { answer: "AUTOPSY", clue: "Postmortem exam for cause of death" },
  { answer: "NECROPSY", clue: "Another word for a postmortem exam" },
  { answer: "GROSS", clue: "Death rate type using all discharges" },
  { answer: "NET", clue: "Death rate type excluding under-48-hour deaths" },
  { answer: "FETAL", clue: "Death of a product of conception before birth" },
  { answer: "MATERNAL", clue: "Death rate for obstetric causes" },
  { answer: "PUERPERAL", clue: "Relating to the period after childbirth" },
  { answer: "STILLBIRTH", clue: "Delivery of a nonliving infant" },
  { answer: "ANESTHESIA", clue: "Death rate tied to agents given before surgery" },
  { answer: "NOSOCOMIAL", clue: "Hospital-acquired, as an infection" },
  { answer: "SEPSIS", clue: "Bloodstream infection tracked as a complication" },
  { answer: "INFECTION", clue: "Invasion by a harmful organism" },
  { answer: "SURGERY", clue: "Operative care whose deaths are rate-tracked" },
  { answer: "OPERATION", clue: "Single surgical procedure episode" },
  { answer: "CESAREAN", clue: "Surgical delivery with its own rate" },
  { answer: "OBSTETRIC", clue: "Relating to childbirth care" },
  { answer: "DELIVERY", clue: "Birth event counted in OB statistics" },
  { answer: "CONSULT", clue: "Opinion from a second physician" },
  { answer: "READMIT", clue: "Take a patient back within 30 days" },
  { answer: "RATE", clue: "Part compared with whole, times 100" },
  { answer: "RATIO", clue: "One quantity divided by another" },
  { answer: "PERCENT", clue: "Portion per hundred" },
  { answer: "NUMERATOR", clue: "Top of a fraction; the part counted" },
  { answer: "DENOM", clue: "Bottom of a rate fraction, informally" },
  { answer: "TOTAL", clue: "Sum of all values" },
  { answer: "SUM", clue: "Result of addition" },
  { answer: "COUNT", clue: "Simple tally of items" },
  { answer: "AVERAGE", clue: "Central value found by dividing a total" },
  { answer: "ROUND", clue: "Reduce to fewer decimal places" },
  { answer: "DECIMAL", clue: "Number with a point and fraction digits" },
  { answer: "STAY", clue: "Time a patient remains hospitalized" },
  { answer: "LOS", clue: "Length of stay, briefly" },
  { answer: "DAYS", clue: "Discharge ___: units summed for average stay" },
  { answer: "UNIT", clue: "Nursing area whose census is reported" },
  { answer: "WARD", clue: "Traditional multi-bed nursing area" },
  { answer: "NOMINAL", clue: "Scale of names with no order" },
  { answer: "ORDINAL", clue: "Scale that ranks but lacks equal intervals" },
  { answer: "INTERVAL", clue: "Scale with equal gaps and no true zero" },
  { answer: "DISCRETE", clue: "Countable, as whole-number data" },
  { answer: "CONTINUOUS", clue: "Measurable on an unbroken scale" },
  { answer: "QUALITATIVE", clue: "Describing categories, not amounts" },
  { answer: "NUMERIC", clue: "Expressed in figures" },
  { answer: "BINARY", clue: "Having only two possible values" },
  { answer: "DATA", clue: "Raw facts before interpretation" },
  { answer: "TALLY", clue: "Running count kept with marks" },
  { answer: "FIELD", clue: "Single element of a database record" },
  { answer: "RECORD", clue: "Row of related data elements" },
  { answer: "TABLE", clue: "Rows and columns of organized values" },
  { answer: "ROW", clue: "Horizontal line in a data table" },
  { answer: "COLUMN", clue: "Vertical line in a data table" },
  { answer: "CELL", clue: "Single box where row meets column" },
  { answer: "CHART", clue: "Graphic display of values" },
  { answer: "GRAPH", clue: "Picture of numeric relationships" },
  { answer: "HISTOGRAM", clue: "Bar display for continuous data classes" },
  { answer: "PIE", clue: "___ chart: circle divided into slices" },
  { answer: "BAR", clue: "___ chart: rectangles compare categories" },
  { answer: "LINE", clue: "___ graph: points joined to show trend" },
  { answer: "SCATTER", clue: "___ plot: dots showing two variables" },
  { answer: "PICTOGRAM", clue: "Display using repeated small symbols" },
  { answer: "AXIS", clue: "Reference line on a graph" },
  { answer: "LEGEND", clue: "Key explaining a chart's colors" },
  { answer: "TITLE", clue: "Heading atop a table or figure" },
  { answer: "LABEL", clue: "Text identifying a chart element" },
  { answer: "SCALE", clue: "Spacing of values along an axis" },
  { answer: "TREND", clue: "General direction over time" },
  { answer: "PLOT", clue: "Mark data points on a grid" },
  { answer: "GRID", clue: "Background lines aiding chart reading" },
  { answer: "CONTROL", clue: "___ chart: display with upper and lower limits" },
  { answer: "RUN", clue: "___ chart: simple plot of points over time" },
  { answer: "PARETO", clue: "Chart ranking causes by frequency" },
  { answer: "DASHBOARD", clue: "Screen of key indicators at a glance" },
  { answer: "REPORT", clue: "Formal presentation of findings" },
  { answer: "POPULATION", clue: "Entire group under study" },
  { answer: "SAMPLE", clue: "Subset drawn from a larger group" },
  { answer: "RANDOM", clue: "Chosen purely by chance" },
  { answer: "SYSTEMATIC", clue: "Sampling by choosing every nth case" },
  { answer: "STRATIFIED", clue: "Sampling from defined subgroups" },
  { answer: "CLUSTER", clue: "Sampling whole naturally occurring groups" },
  { answer: "STRATUM", clue: "One subgroup used in layered sampling" },
  { answer: "BIAS", clue: "Systematic error skewing results" },
  { answer: "ERROR", clue: "Difference between measured and true value" },
  { answer: "CHANCE", clue: "Randomness, as a rival explanation" },
  { answer: "NULL", clue: "___ hypothesis: statement of no difference" },
  { answer: "ALPHA", clue: "Preset significance threshold" },
  { answer: "PVALUE", clue: "Probability a result arose by chance" },
  { answer: "TTEST", clue: "Comparison of two group means" },
  { answer: "CHISQUARE", clue: "Test for association in a table of counts" },
  { answer: "ANOVA", clue: "Test comparing three or more means" },
  { answer: "POWER", clue: "Ability of a study to detect a real effect" },
  { answer: "CONFIDENCE", clue: "___ interval: plausible range for an estimate" },
  { answer: "ESTIMATE", clue: "Value inferred from sample data" },
  { answer: "INFERENCE", clue: "Drawing conclusions about a whole from a part" },
  { answer: "CORRELATE", clue: "Vary together, as two measures" },
  { answer: "CAUSATION", clue: "One factor actually producing another" },
  { answer: "CONFOUND", clue: "Hidden third factor muddying a link" },
  { answer: "REGRESSION", clue: "Modeling one variable from another" },
  { answer: "PREDICTOR", clue: "Variable used to forecast an outcome" },
  { answer: "OUTCOME", clue: "Result being measured in a study" },
  { answer: "VALIDITY", clue: "Degree a tool measures what it should" },
  { answer: "RELIABLE", clue: "Yielding consistent results on repeat" },
  { answer: "VARIABLE", clue: "Characteristic that can take many values" },
  { answer: "INDEPENDENT", clue: "Variable manipulated by the researcher" },
  { answer: "DEPENDENT", clue: "Variable that responds to another" },
  { answer: "COHORT", clue: "Group followed forward in time" },
  { answer: "PROSPECTIVE", clue: "Looking forward from exposure to outcome" },
  { answer: "RETRO", clue: "Backward-looking, in study design shorthand" },
  { answer: "LONGITUDINAL", clue: "Following subjects over an extended span" },
  { answer: "CASE", clue: "___ control: design comparing sick and well" },
  { answer: "MATCH", clue: "Pair a case with a similar unaffected subject" },
  { answer: "TRIAL", clue: "Planned experiment on an intervention" },
  { answer: "BLIND", clue: "Design where subjects don't know their group" },
  { answer: "PLACEBO", clue: "Inactive treatment used for comparison" },
  { answer: "PROTOCOL", clue: "Written plan governing a study" },
  { answer: "HYPOTHESIS", clue: "Testable statement proposed in advance" },
  { answer: "EPIDEMIC", clue: "Sharp rise in cases beyond expected" },
  { answer: "PANDEMIC", clue: "Outbreak crossing many countries" },
  { answer: "INCIDENCE", clue: "New cases arising in a period" },
  { answer: "PREVALENCE", clue: "All existing cases at a point in time" },
  { answer: "ENDEMIC", clue: "Constantly present in an area" },
  { answer: "VECTOR", clue: "Organism carrying disease between hosts" },
  { answer: "REGISTRY", clue: "Organized collection on one disease" },
  { answer: "TUMOR", clue: "Growth tracked in a cancer registry" },
  { answer: "ABSTRACT", clue: "Pull key data from a record for a registry" },
  { answer: "NATALITY", clue: "Birth statistics, formally" },
  { answer: "BIRTH", clue: "Vital event with its own rate" },
  { answer: "CERTIFICATE", clue: "Legal document filed at death or birth" },
  { answer: "CORONER", clue: "Official who may order a postmortem" },
  { answer: "VITAL", clue: "Kind of statistics on births and deaths" },
  { answer: "PUBLIC", clue: "___ health: population-level care field" },
  { answer: "SURVEY", clue: "Structured questioning of a sample" },
  { answer: "QUESTION", clue: "Single item on a survey form" },
  { answer: "RESPONSE", clue: "___ rate: share of those who reply" },
  { answer: "WAREHOUSE", clue: "Central store of integrated historical data" },
  { answer: "MART", clue: "Small subject-specific slice of a warehouse" },
  { answer: "ETL", clue: "Extract, transform, load, briefly" },
  { answer: "QUERY", clue: "Request for specific data" },
  { answer: "SQL", clue: "Language for questioning a database" },
  { answer: "SCHEMA", clue: "Blueprint of a database's structure" },
  { answer: "INDEX", clue: "Structure speeding up data lookup" },
  { answer: "KEY", clue: "Field uniquely identifying a record" },
  { answer: "JOIN", clue: "Combine two tables on a shared field" },
  { answer: "FILTER", clue: "Narrow results to matching rows" },
  { answer: "SORT", clue: "Arrange values in order" },
  { answer: "PIVOT", clue: "Table that summarizes by dragging fields" },
  { answer: "EXCEL", clue: "Microsoft spreadsheet used for analysis" },
  { answer: "FORMULA", clue: "Expression computing a spreadsheet value" },
  { answer: "MACRO", clue: "Recorded set of automated steps" },
  { answer: "METRIC", clue: "Standard measure being tracked" },
  { answer: "MEASURE", clue: "Quantity captured for evaluation" },
  { answer: "BENCHMARK", clue: "Reference standard for comparison" },
  { answer: "TARGET", clue: "Goal value a metric aims at" },
  { answer: "KPI", clue: "Key performance indicator, briefly" },
  { answer: "PREDICTIVE", clue: "Analytics forecasting what will happen" },
  { answer: "DESCRIPTIVE", clue: "Analytics summarizing what has happened" },
  { answer: "MINING", clue: "Digging patterns out of large data sets" },
  { answer: "MODEL", clue: "Simplified representation used to predict" },
  { answer: "ALGORITHM", clue: "Step-by-step computational rule" },
  { answer: "BIG", clue: "___ data: high volume, velocity, variety" },
  { answer: "VOLUME", clue: "Sheer amount of data, one of the V's" },
  { answer: "VELOCITY", clue: "Speed at which data arrives" },
  { answer: "VARIETY", clue: "Mix of data formats, one of the V's" },
  { answer: "STRUCTURED", clue: "Data neatly fitting fixed fields" },
  { answer: "TEXT", clue: "Unstructured narrative data type" },
  { answer: "VISUAL", clue: "Relating to graphic data presentation" },
  { answer: "AGGREGATE", clue: "Combine detail into summary totals" },
  { answer: "GRANULAR", clue: "Fine in level of detail" },
  { answer: "NORMALIZE", clue: "Restructure tables to cut redundancy" },
  { answer: "DIRTY", clue: "Describing data full of errors" },
  { answer: "SCRUB", clue: "Clean errors out of a data set" },
  { answer: "ACCURACY", clue: "Data quality trait of being correct" },
  { answer: "CURRENCY", clue: "Data quality trait of being up to date" },
  { answer: "COMPLETE", clue: "Missing no required data elements" },
  { answer: "TIMELY", clue: "Available when needed" },
  { answer: "PRECISION", clue: "Fineness and consistency of measurement" },
  { answer: "AUDIT", clue: "Systematic review checking data integrity" },
  { answer: "INTEGRITY", clue: "Data's wholeness and trustworthiness" }
]
